//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Petteys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer2
    {
        public Customer2()
        {
            this.Orders = new HashSet<Orders>();
        }
    
        public int Cus_Id2 { get; set; }
        public int Customer_id { get; set; }
        public string cus_name { get; set; }
        public string cus_bank { get; set; }
        public string name_bank { get; set; }
        public string id_bank { get; set; }
        public string card_no { get; set; }
        public string images { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual ICollection<Orders> Orders { get; set; }
    }
}
