//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Petteys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public Orders()
        {
            this.Order_details = new HashSet<Order_details>();
        }
    
        public int order_Id { get; set; }
        public int Product_id { get; set; }
        public int Product_id2 { get; set; }
        public int Product_id3 { get; set; }
        public int cus_id { get; set; }
        public int cus_id2 { get; set; }
        public string name { get; set; }
        public decimal price { get; set; }
        public decimal amount { get; set; }
        public decimal total { get; set; }
        public System.DateTime order_date { get; set; }
        public System.DateTime ship_date { get; set; }
        public string Order_status { get; set; }
        public string Remark { get; set; }
        public string image { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Customer2 Customer2 { get; set; }
        public virtual ICollection<Order_details> Order_details { get; set; }
        public virtual Pet Pet { get; set; }
        public virtual Product Product { get; set; }
        public virtual Trainer Trainer { get; set; }
    }
}
