//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Petteys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_details
    {
        public int Order_details_id { get; set; }
        public int orders_id { get; set; }
        public int Product_id { get; set; }
        public int Product_id2 { get; set; }
        public int Product_id3 { get; set; }
        public Nullable<int> amount { get; set; }
        public Nullable<decimal> Sub_total { get; set; }
    
        public virtual Orders Orders { get; set; }
        public virtual Pet Pet { get; set; }
        public virtual Product Product { get; set; }
        public virtual Trainer Trainer { get; set; }
    }
}
