//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Petteys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Popular
    {
        public int Id { get; set; }
        public int product_id { get; set; }
        public int product_id2 { get; set; }
        public int product_id3 { get; set; }
        public string name { get; set; }
        public int point { get; set; }
        public decimal price { get; set; }
    
        public virtual Pet Pet { get; set; }
        public virtual Product Product { get; set; }
        public virtual Trainer Trainer { get; set; }
    }
}
