// <auto-generated />
namespace HW2_B5970704.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class oatcustomer : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(oatcustomer));
        
        string IMigrationMetadata.Id
        {
            get { return "201808230918274_oatcustomer"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
